// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://maqpxgmmzhmnuhdsjlqc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1hcXB4Z21temhtbnVoZHNqbHFjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg0MDg5MzYsImV4cCI6MjA3Mzk4NDkzNn0.GWGLmXCgwS8P5C1fIoPEts-95jD9QLD7xhXwHPrxyk0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});